# Site Settings
locale: "en-US"
title: "TimilsinaRC"
title_separator: "-"
subtitle: "Visiting Lecturer of Engineering Mathematics"
name: "Ramchandra Timilsina"
description: "Visiting Lecturer of Engineering Mathematics at Kathmandu University"
url: "https://github.io"
baseurl: ""
repository: "TimilsinaRC07/TimilsinaRC07.github.io"
markdown: kramdown
highlighter: rouge
words_per_minute: 200

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Theme Layout defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true

# Author Details (Sidebar)
author:
  name: "Ramchandra Timilsina"
  avatar: "https://githubusercontent.com"
  bio: "Visiting Lecturer of Engineering Mathematics at Kathmandu University"
  location: "Dhulikhel, Nepal"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:timilsinarc07@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://github.io/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://youtube.com"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org"

# Site Footer
footer:
  links:
    - label: "GitHub"
      url: "https://github.com"
